name: UI-Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:

  UItest:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Make launch script executable
        run: chmod +x ./launch.sh

      - name: Run launch script
        run: ./launch.sh

      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2 #boots up emulator and perform UI tests
        with:
          api-level: 28
          script: ./gradlew connectedCheck

      - name: Make stop script executable
        if: always()
        run: chmod +x ./stop.sh

      - name: Run stop script
        if: always()
        run: ./stop.sh